const CLASSES = {
    INFORMATION: 'INFORMATION',
    SUCCESSFUL: 'SUCCESSFUL',
    REDIRECTION: 'REDIRECTION',
    CLIENT_ERROR: 'CLIENT_ERROR',
    SERVER_ERROR: 'SERVER_ERROR'
};

export const {INFORMATION, SUCCESSFUL, REDIRECTION, CLIENT_ERROR, SERVER_ERROR} = CLASSES;
export default CLASSES;
