//** COURSE ACTIONS **//
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';

//** INVENTORY ACTIONS **//
export const LOAD_INVENTORY_SUCCESS = 'LOAD_INVENTORY_SUCCESS';
export const UPDATE_INVENTORY_SUCCESS = 'UPDATE_INVENTORY_SUCCESS';
export const CREATE_INVENTORY_SUCCESS = 'CREATE_INVENTORY_SUCCESS';
export const DELETE_INVENTORY_SUCCESS = 'DELETE_INVENTORY_SUCCESS';

//** ARTICLE ACTIONS **//
export const LOAD_ARTICLES_SUCCESS = 'LOAD_ARTICLES_SUCCESS';
export const UPDATE_ARTICLE_SUCCESS = 'UPDATE_ARTICLE_SUCCESS';
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS';
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';

//** WAREHOUSE ACTIONS **//
export const LOAD_WAREHOUSES_SUCCESS = 'LOAD_WAREHOUSES_SUCCESS';
export const UPDATE_WAREHOUSE_SUCCESS = 'UPDATE_WAREHOUSE_SUCCESS';
export const CREATE_WAREHOUSE_SUCCESS = 'CREATE_WAREHOUSE_SUCCESS';
export const DELETE_WAREHOUSE_SUCCESS = 'DELETE_WAREHOUSE_SUCCESS';

//** LOCATION ACTIONS **//
export const LOAD_LOCATIONS_SUCCESS = 'LOAD_LOCATIONS_SUCCESS';
export const UPDATE_LOCATION_SUCCESS = 'UPDATE_LOCATION_SUCCESS';
export const CREATE_LOCATION_SUCCESS = 'CREATE_LOCATION_SUCCESS';
export const DELETE_LOCATION_SUCCESS = 'DELETE_LOCATION_SUCCESS';

//** LOCATION TAG ACTIONS **//
export const LOAD_LOCATION_TAGS_SUCCESS = 'LOAD_LOCATION_TAGS_SUCCESS';
export const UPDATE_LOCATION_TAG_SUCCESS = 'UPDATE_LOCATION_TAG_SUCCESS';
export const CREATE_LOCATION_TAG_SUCCESS = 'CREATE_LOCATION_TAG_SUCCESS';

//** USER ACTIONS **//
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';

//** ACTIVE USER ACTIONS **//
export const UPDATE_ACTIVE_USER_SUCCESS = 'UPDATE_ACTIVE_USER_SUCCESS';
export const CREATE_ACTIVE_USER_SUCCESS = 'CREATE_ACTIVE_USER_SUCCESS';

//** AUTHOR ACTIONS **//
export const  LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';

//** AJAX ACTIONS **//
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';


